language: node_js
node_js:
  - "0.10"
env:
  global:
    - secure: A8G7W53D9vz/LAv33VlXPWgQzqjU7b+ioMDU0BHORxogAsb7hQoA2LxMqJgxUasT5e0GJsOBzmYbi6lUouijq+MFID0aJE+J/UlEU8qAsrg2MgYtG1RvX0xL13nqK3iLiObWtjK3/hBGf/CVPwphMq3zLIGcb9Js5vQPd1xtdLjTmkI45SUr6oNDD86L/RZ1SZSQdl02qUzQ7tLnsFtE/oX9VEW1pwJ3EBePq7MXuULM2KQvCreb/XmkkcoYIsWEx4/83ksaRh7YB3wwMcOGXIPdlXI+UCpIbzQrK/1AXHdfQyQ+OQzXLkKR/ntvvgEqH5VskI+pJ900c6Guw/dZQAznbrjfIjszEnT79YBF+15YM+mrnaXYVixExCmPSKQ08UesalqRbY1ObxeQyQsk+MKT0NgSDURmiNmcyRbtQI3CLag8q6eTEAS3UEXPPl1nxDHtZACodzGtYzBwLWWccMGuSR4cz4cx/f7moqgxLr9DnG5PlE+rgnpX+ftraVN83EEuBG+SwIjDzuNJSc+Tt7f7SYqmtaqUQKfgL0tZIxntWdIeBnAagNW+cfuedLnl6yBd7xT37MXEVR7Ymp18xYyEY2D6aMM/DhHv9c6r0Sq87TOqLGM0cxvod53WfGkuGV5XLnF9mlgSNJkxzhsRBCev9X2/FmaZn1e7VfuCreU=
    - secure: qU1ImWuBYsz7ofdBK1N3E1tKMyIERN+eTeaS09xm9npre+My838glsumeSig8gDFQS0Gv1fbW4UW6WWgaxHjzRjCd72GrifGHa0aKDpVjgAiwGhwj7WycNxD5XzLA++czoRxEYGDnWdQwFg4ZS5CL3uE0GVRDifEa7cyxO18JmbwfCNMBVLsLE5p4il88SiZgkA9LHQfvYrF595K2a7tJIX8ElD7jYdl2vtaewmO2KcjwpwwcmndPLTwsfdpehiRr83obTvM0k8iT0H11WsJEKKTUFNdfY3SqNvSMZJF92dr0/CB1JSSevGa8IX/LqhThJsT4UpEOZFkNDWTFPUDIcxTOFfSJSJVLfyjCEUjmUnQ+tic8GsYS98guW6M1gmVRVqrs9l8sU57EpJRl1ppszasaa2MduhHEMD7LFVcYxw3Xip7XcYtl0vAhuF0djymyd/kneDGpTFwXj1hubke5t3i0sycU7Nxtx/3c1AWSbqoRnVIjeYhthtszxhBDAXnhA7mGLVsGtLHCXI6mN3VF7guUtbjSG2zvKsQswVe/emJlVoicPlHYyIpVysUvZ7KyErvbnyhwfXnZaZwJzEwsLkHcXlZNdcY9WKnKcKwy3xZ99UJIbL1TxUSpV8UUxLJ+wKvRVjvRy6Q+NHI7tldvuwJ4J1kC8i0ML6jY62ph8A=

install:
   - npm install -g grunt-cli
   - npm -g install bower
   - npm install
   - bower install

script:
   - grunt jshint test:remote

